
import __ASTRO_IMAGE_IMPORT_1YLePS from "../web-reaper/avatar.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fauthors%2Fweb-reaper%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1P9Y6C from "../second-author/avatar.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fauthors%2Fsecond-author%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZsqLk0 from "../example-one/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-one%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z2tVl6q from "../example-three/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-three%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1jaxTN from "../example-two/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-two%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1cYqGB from "../example-deux/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Fexample-deux%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1HyAJ8 from "../tailwind-gradient-underline/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftailwind-gradient-underline%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_2hUUhY from "../example-un/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Fexample-un%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1C43qi from "../tailwind-gradient-underline/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Ftailwind-gradient-underline%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z2hJJmq from "../best-vscode-extensions-front-end-developers/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fbest-vscode-extensions-front-end-developers%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z9jUBs from "../tsconfig-paths-setup/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftsconfig-paths-setup%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZPsEiB from "../best-vscode-extensions-front-end-developers/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Fbest-vscode-extensions-front-end-developers%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_TdHED from "../example-trois/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Fexample-trois%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZGsXSV from "../tsconfig-paths-setup/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Ftsconfig-paths-setup%2Findex.mdx";
export default new Map([["../web-reaper/avatar.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fauthors%2Fweb-reaper%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1YLePS], ["../second-author/avatar.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fauthors%2Fsecond-author%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1P9Y6C], ["../example-one/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-one%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZsqLk0], ["../example-three/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-three%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z2tVl6q], ["../example-two/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-two%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1jaxTN], ["../example-deux/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Fexample-deux%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1cYqGB], ["../tailwind-gradient-underline/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftailwind-gradient-underline%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1HyAJ8], ["../example-un/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Fexample-un%2Findex.mdx", __ASTRO_IMAGE_IMPORT_2hUUhY], ["../tailwind-gradient-underline/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Ftailwind-gradient-underline%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1C43qi], ["../best-vscode-extensions-front-end-developers/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fbest-vscode-extensions-front-end-developers%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z2hJJmq], ["../tsconfig-paths-setup/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftsconfig-paths-setup%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z9jUBs], ["../best-vscode-extensions-front-end-developers/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Fbest-vscode-extensions-front-end-developers%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZPsEiB], ["../example-trois/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Fexample-trois%2Findex.mdx", __ASTRO_IMAGE_IMPORT_TdHED], ["../tsconfig-paths-setup/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Ftsconfig-paths-setup%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZGsXSV]]);
		